---
name: Quentin
surname: Facon-Barillot
position: "Doctorant en psychologie clinique"
address: "Maisons Laffitte, France"
profilepic: "./img/me.jpg"
email: "quentin.d.barillot@gmail.com"
github: QuentinBARILLOT
linkedin: quentin-barillot
orcid: 0000-0002-9469-3623
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: '0a51cd'
aboutme: "Psychologue clinicien et psychothérapeute, je suis en doctorat de psychologie clinique et mes travaux portent sur la santé mentale des étudiants."
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'
             ,'markdown'  # String Manipulation
            )

xfun::pkg_attach2(packages, message = FALSE)

source(file = "./r/data.R", encoding = "UTF-8")

```

# Expériences professionnelles

## Enseignement et recherche

```{r ens_rech}

exp_ens_rech %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = where,
    where = glue::glue("{startMonth} {startYear} → {endMonth} {endYear}",.na = "")
  )
    

```

## Clinique

```{r clinique}

exp_cli %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = where,
    where = glue::glue("{startMonth} {startYear} → {endMonth} {endYear}",.na = "")
  )

```

## Autres

```{r autre}

exp_oth %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = where,
    where = glue::glue("{startMonth} {startYear} → {endMonth} {endYear}",.na = "")
  )

```

# Enseignements

```{r ens}

ens %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = where,
    where = when
  )

```

# Cursus universitaire

```{r cursus}

cursus %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = where,
    where = glue::glue("{startYear} → {endYear}",.na = "")
  )

```

# Formations

## Recherche

```{r formations_rec}

formation_rec %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = where,
    where = glue::glue("{startYear} → {endYear}",.na = "")
  )

```

## Clinique

```{r formations_cli}

formation_cli %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = where,
    where = glue::glue("{startYear} → {endYear}",.na = "")
  )

```

# Publications et communications

## Chapitres d'ouvrages

```{r chapters}

bibliography_entries("./Publications.bib")
```

## Communications orales

```{r oral_com}

bibliography_entries("./présentation orale.bib")
```

## Posters

```{r posters}

bibliography_entries("./Posters.bib")

```

# Congrés

```{r}

conf %>%
  detailed_entries(
    with = congress,
    where = where
  )

```

# Adhésions et allocations

```{r membership}

membership %>%
  detailed_entries(
    with = activities,
    what = unit,
    where = year
  )

```

# Responsabilités admistratives

```{r ADMINISTRATIVE}

adm %>%
  detailed_entries(
    with = precision,
    what = title,
    when = where,
    where = year
  )

```
\newpage 
# Compétences

```{r COMPETENCES}

comp %>%
    detailed_entries(
        what = domain,
        why = detail,
        .protect = F
    )
```
