---
name: Quentin
surname: Facon-Barillot
position: "PHD student in clinical psychology"
address: "Maisons Laffitte, France"
profilepic: "./img/me.jpg"
email: "qbarillot@parisnanterre.fr"
github: QuentinBARILLOT
linkedin: quentin-barillot
orcid: 0000-0002-9469-3623
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: '0a51cd'
aboutme: "As a clinical psychologist and psychotherapist, I have been working for more than a year on a PHD in clinical psychology on student mental health under the supervision of Lucia Romo and Yannick Morvan. I also carry out voluntary consultations for the Fondation Santé des Étudiants de France in Paris (FSEF)."
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'
             ,'markdown'  # String Manipulation
            )

xfun::pkg_attach2(packages, message = FALSE)

source(file = here("r","data_eng.r"))

```

# Professional experiences

```{r EMPLOYMENT}

work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = where,
    where = glue::glue("{startMonth} {startYear} → {endMonth} {endYear}",.na = "")
  )

```

# Qualifications

## Training

```{r EDUCATION1}

edu1 %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = where,
    where = glue::glue("{startYear} → {endYear}",.na = "")
  )

```

## Diplomas

```{r EDUCATION2}

edu2 %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = where,
    where = glue::glue("{startYear} → {endYear}",.na = "")
  )

```

# Publications

```{r PUBLICATIONS}

bibliography_entries("Publications.bib")
```

# Internships

```{r INTERNESHIPS}

intern %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = where,
    where = glue::glue("{startMonth} {startYear} → {endMonth} {endYear}",.na = "")
  )

```

# Congress

## Oral communications

```{r CONFERENCES1}

conf1 %>%
  detailed_entries(
    with = congress,
    what = presentation,
    where = where,
    when = when
  )

```

## Poster sessions

```{r CONFERENCES2}

conf2 %>%
  detailed_entries(
    with = congress,
    what = presentation,
    where = where,
    when = when
  )

```

\pagebreak

# Administrative duties

```{r ADMINISTRATIVE}

adm %>%
  detailed_entries(
    with = precision,
    what = title,
    when = where,
    where = year
  )

```

# Volunteering

```{r BENEVOLAT}

cha %>%
  detailed_entries(
    with = unit,
    what = activities,
    why = detail,
    when = year,
    where = where
  )

```

# Skills 

```{r COMPETENCES}

comp %>%
    detailed_entries(
        what = domain,
        why = detail,
        .protect = F
    )
```
